### PR TITLE
Feat/view customer

### PR DESCRIPTION
**Pull request by Mahmoud-zino**
Ready for Review
1. Customer list/add/edit/delete
2. Pet list/add/edit/delete

### CODE REVIEW

**Comment by cyberfutur** [comment]
@Mahmoud-zino pr should be merged, if its still wip?

**Comment by cyberfutur** [comment]
@Mahmoud-zino customer search isn't working:

image

**Comment by cyberfutur** [comment]
On Deletion Dialog naming is inconsistent (german/german and not german/englisch):

image

**Comment by cyberfutur** [comment]
@Mahmoud-zino i reviewed the rest, except the issues it should be fine.

**Review by cyberfutur — CHANGES_REQUESTED** [review]
fix search and localize the confirm button on customer deletion

**Comment by Mahmoud-zino** [comment]
> @Mahmoud-zino customer search isn't working:
> 
> image

will be resolved by #34

**Review by cyberfutur — APPROVED** [review]

**Pull request merged**
